myMoiveReviews/home/urls.py
from django.urls import path 
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name = "home"),
    path('create', views.create, name ="create"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete"),
]

myMoiveReviews/movieSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace="posts")),
]

myMoiveReviews/home/models.py
from pyexpat import model
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50, verbose_name="제목")
    director = models.CharField(max_length=50, verbose_name="감독")
    main = models.CharField(max_length=50, verbose_name="주연")
    years = models.IntegerField(verbose_name="개봉 년도")
    genre = models.CharField(max_length=50, verbose_name="장르")
    starRating = models.FloatField(verbose_name="별점")
    runningTime = models.IntegerField(verbose_name="러닝타임")
    reviews = models.TextField(verbose_name="리뷰 내용")
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)
    # deleted_at = models.DateTimeField(auto_now=True)

myMoiveReviews/home/views.py
from shutil import move
from django.shortcuts import render, redirect
from .models import Movie

# Create your views here.
def home(request):
    movies = Movie.objects.all()
    context={
        "movies":movies
    }

    return render(request, template_name="posts/home.html", context=context)

def create(request):
    if request.method =="POST":
        title = request.POST["title"]
        director = request.POST["director"]
        main = request.POST["main"]
        years = request.POST["years"]
        genre = request.POST["genre"]
        starRating = request.POST["starRating"]
        runningTime = request.POST["runningTime"]
        reviews = request.POST["reviews"]

        Movie.objects.create(title=title, director=director, main=main, years=years, genre=genre, starRating=starRating, runningTime=runningTime, reviews=reviews)
        return redirect("/")
    context={

    }

    return render(request, template_name="posts/create.html", context=context)

def detail(request, id):
    movie = Movie.objects.get(id=id)
    context={"movie":movie}
    return render(request, template_name="posts/detail.html", context=context)

def update(request, id):
    if request.method == "POST":
        title = request.POST["title"]
        director = request.POST["director"]
        main = request.POST["main"]
        years = request.POST["years"]
        genre = request.POST["genre"]
        starRating = request.POST["starRating"]
        runningTime = request.POST["runningTime"]
        reviews = request.POST["reviews"]

        Movie.objects.filter(id=id).update(title=title, director=director,
        main=main, years=years, genre=genre, starRating=starRating, runningTime=runningTime,
        reviews=reviews)
        return redirect("/")

    elif request.method == "GET":
        movie = Movie.objects.get(id=id)
        context={"movie":movie}
        return render(request, template_name="posts/update.html", context=context)

def delete(request, id):
    if request.method == "POST":
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect("/")

myMoiveReviews/home/templates/posts/create.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>영화 리뷰 올리기</title>
  </head>
  <body>
    <form action="{% url 'posts:create' %}" method="post">
      {% csrf_token %}
      <h2>
        <input type="text" name="title" placeholder="제목" />
      </h2>
      <p>
        <input type="text" name="director" placeholder="감독" />
        <input type="text" name="main" placeholder="주연" />
        <input type="number" name="years" placeholder="개봉 년도" />
      </p>
      <p>
        <input type="text" name="genre" placeholder="장르" />
        <input type="number" step="0.01" name="starRating" placeholder="별점" />
        <input type="number" name="runningTime" placeholder="러닝타임" />
      </p>
      <textarea name="reviews" id="" cols="50" rows="10"></textarea>
      <div>
        <input type="submit" value="저장" />
      </div>
    </form>
  </body>
</html>

myMoiveReviews/home/templates/posts/detail.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>영화 리뷰</title>
  </head>
  <body>
    <article>
      <h2>제목 : {{ movie.title }}</h2>
      <p>감독: {{ movie.director }} 주연: {{movie.main}}</p>
      <p>개봉 년도: {{movie.year}} 장르: {{movie.genre}}</p>
      <p>별점: {{movie.starRating}} 러닝타임: {{movie.runningTime}}분</p>
      <div>{{movie.reviews}}</div>
    </article>
    <div><a href="{% url 'posts:home' %}">my Movie reviews</a></div>
    <div><a href="{% url 'posts:update' movie.id %}">수정</a></div>
    <form action="{% url 'posts:delete' movie.id %}" method="post">
      {% csrf_token %}
      <button>삭제</button>
    </form>
  </body>
</html>

myMoiveReviews/home/templates/posts/home.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>홈 화면</title>
  </head>
  <body>
    <nav>
      <a href="{% url 'posts:create' %}">리뷰 작성</a>
    </nav>
    {% for movie in movies %}
    <article>
      <h1>
        <a href="{% url 'posts:detail' movie.id %}">{{movie.title}}</a>
      </h1>
      <p>{{movie.years}}</p>
      <p>{{movie.genre}}</p>
      <p>{{movie.starRating}}</p>
    </article>
    {% endfor %}
  </body>
</html>

myMoiveReviews/home/templates/posts/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>게시글 올리기</title>
  </head>
  <body>
    <form action="{% url 'posts:update' movie.id %}" method="post">
      {% csrf_token %}
      <h2>
        <input
          type="text"
          name="title"
          placeholder="제목"
          value="{{movie.title}}"
        />
      </h2>
      <p>
        <input
          type="text"
          name="director"
          placeholder="감독"
          value="{{movie.director}}"
        />
        <input
          type="text"
          name="main"
          placeholder="주연"
          value="{{movie.main}}"
        />
        <input
          type="number"
          name="years"
          placeholder="개봉 년도"
          value="{{movie.years}}"
        />
      </p>
      <p>
        <input
          type="text"
          name="genre"
          placeholder="장르"
          value="{{movie.genre}}"
        />
        <input
          type="number"
          step="0.01"
          name="starRating"
          placeholder="별점"
          value="{{movie.starRating}}"
        />
        <input
          type="number"
          name="runningTime"
          placeholder="러닝타임"
          value="{{movie.runningTime}}"
        />
      </p>
      <textarea name="reviews" id="" cols="50" rows="10">
{{movie.reviews}}</textarea
      >

      <div>
        <a href="{% url 'posts:home' %}"
          ><input type="submit" value="저장"
        /></a>
      </div>
    </form>
  </body>
</html>