SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('swideaSite.urls')),
]

SWIDEA_SITE/swideaSite/urls.py
from django.urls import path 
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "sites"

urlpatterns = [
    path('', views.main, name = "main"),
    path('ideacreate', views.ideacreate, name = "ideacreate"),
    path('idea/<int:id>', views.ideadetail, name = "ideadetail"),
    path('ideaupdate/<int:id>', views.ideaupdate, name = "ideaupdate"),
    path('ideadelete/<int:id>', views.ideadelete, name = "ideadelete"),
    path('devtlist', views.devtlist, name="devtlist"),
    path('devtcreate', views.devtcreate, name = "devtcreate"),
    path('devtdetail/<int:id>', views.devtdetail, name = "devtdetail"),
    path('devtupdate/<int:id>', views.devtupdate, name = "devtupdate"),
    path('devtdelete/<int:id>', views.devtdelete, name = "devtdelete"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/swideaSite/models.py
from email import contentmanager
from unicodedata import category
from django.db import models

# Create your models here.
class Devtool(models.Model):
    name = models.CharField(max_length=50, verbose_name="이름")
    kind = models.CharField(max_length=50, verbose_name="종류")
    content = models.TextField(verbose_name="개발툴 설명")

class Idea(models.Model):
    title = models.CharField(max_length=50, verbose_name="아이디어명")
    image = models.ImageField(blank = True, upload_to='', verbose_name="Image")
    content = models.TextField(verbose_name="아이디어 설명")
    interest = models.IntegerField(default = 0, verbose_name="아이디어 관심도")
    devtool = models.ForeignKey(Devtool, on_delete=models.CASCADE, related_name="tool_name")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

SWIDEA_SITE/swideaSite/views.py
from django.shortcuts import render, redirect

from swideaSite.models import Devtool, Idea

# Create your views here.
def main(request):
    sort = request.GET.get('sort', None)
    if sort == "name":
        ideas = Idea.objects.all().order_by('title')
    elif sort == "recent":
        ideas = Idea.objects.all().order_by('updated_at')
    elif sort == "postly":
        ideas = Idea.objects.all().order_by('created_at')
    else:
        ideas = Idea.objects.all()
    context={
        "ideas":ideas
    }
    return render(request, template_name="sites/main.html", context=context)

def ideacreate(request):
    if request.method =="POST":
        print(request.POST)
        title = request.POST["title"]
        req_image = request.FILES["image"]
        content = request.POST["content"]
        interest = request.POST["interest"]
        devtname = request.POST["devtool"]
        devtool = Devtool.objects.get(name=devtname)

        Idea.objects.create(title=title, image=req_image, content=content, interest=interest, devtool=devtool)
        return redirect("/")
    devtools = Devtool.objects.all()
    context = {
        "devtools":devtools
    }

    return render(request, template_name="sites/ideacreate.html", context=context)

def ideaupdate(request, id):
    if request.method == "POST":
        title = request.POST["title"]
        req_image = request.FILES["image"]
        content = request.POST["content"]
        interest = request.POST["interest"]
        devtname = request.POST["devtool"]
        devtool = Devtool.objects.get(name=devtname)

        Idea.objects.filter(id=id).update(title=title, image=req_image, content=content, interest=interest, devtool=devtool)
        return redirect("/")

    elif request.method == "GET":
        idea = Idea.objects.get(id=id)
        devtools = Devtool.objects.all()
        devt_name = idea.devtool.name
        context={"idea":idea,
        "devt_name":devt_name,
        "devtools":devtools,
        }
        return render(request, template_name="sites/ideaupdate.html", context=context)

def ideadetail(request, id):
    idea = Idea.objects.get(id=id)
    devt_name = idea.devtool.name

    context={
        "idea":idea,
        "devt_name":devt_name,
    }
    return render(request, template_name="sites/ideadetail.html", context=context)

def ideadelete(request, id):
    if request.method == "POST":
        idea = Idea.objects.get(id=id)
        idea.delete()
        return redirect("/")

def devtcreate(request):
    if request.method =="POST":
        print(request.POST)
        name = request.POST["name"]
        kind = request.POST["kind"]
        content = request.POST["content"]

        Devtool.objects.create(name=name, kind=kind, content=content)
        return redirect("/devtlist")
        
    context = {
    }

    return render(request, template_name="sites/devtcreate.html", context=context)

def devtlist(request):
    devtools = Devtool.objects.all()
    context={
        "devtools":devtools
    }
    return render(request, template_name="sites/devtlist.html", context=context)

def devtdetail(request, id):
    devtool = Devtool.objects.get(id=id)

    all_idea = devtool.tool_name.all()
    context={
        "devtool":devtool,
        "all_idea":all_idea,
    }
    return render(request, template_name="sites/devtdetail.html", context=context)

def devtupdate(request, id):
    if request.method =="POST":
        print(request.POST)
        name = request.POST["name"]
        kind = request.POST["kind"]
        content = request.POST["content"]

        Devtool.objects.filter(id=id).update(name=name, kind=kind, content=content)
        return redirect("/devtlist")

    elif request.method == "GET":
        devtool = Devtool.objects.get(id=id)
        context={
            "devtool":devtool
        }
        return render(request, template_name="sites/devtupdate.html", context=context)

def devtdelete(request, id):
    if request.method == "POST":
        devtool = Devtool.objects.get(id=id)
        devtool.delete()
        return redirect("/devtlist")

SWIDEA_SITE/swideaSite/templates/sites/devtcreate.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>개발툴 등록</title>
  </head>
  <body>
    <nav>
      <a href="">My SW Idea Manage</a>
      <a href="{% url 'sites:ideacreate' %}">아이디어 등록</a>
      <a href="{% url 'sites:main' %}">아이디어 관리</a>
      <a href="{% url 'sites:devtcreate' %}">개별툴 등록</a>
      <a href="{% url 'sites:devtlist' %}">개별툴 관리</a>
    </nav>
    <form
      action="{% url 'sites:devtcreate' %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <p>
        이름:
        <input type="text" name="name" />
      </p>
      <p>
        종류:
        <input type="text" name="kind" />
      </p>
      <p>
        개발툴 설명:
        <textarea name="content" id="" cols="30" rows="10"></textarea>
      </p>
      <div>
        <input type="submit" value="SUBMIT" />
      </div>
    </form>
  </body>
</html>

SWIDEA_SITE/swideaSite/templates/sites/devtdetail.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>개발툴 상세</title>
  </head>
  <body>
    <article>
      <div>
        <h2>{{ devtool.title }}</h2>
        <p>{{devtool.kind}}</p>
        <p>{{devtool.content}}</p>
      </div>
      <div>
        {% for idea in all_idea %}
        <a href="{% url 'sites:ideadetail' idea.id %}">{{ idea.title }}</a>
        {% endfor %}
      </div>
    </article>
    <div><a href="{% url 'sites:devtupdate' devtool.id %}">수정</a></div>
    <div>
      <form action="{% url 'sites:devtdelete' devtool.id %}" method="post">
        {% csrf_token %}
        <button>삭제</button>
      </form>
    </div>
    <div><a href="/devtlist">목록</a></div>
  </body>
</html>

SWIDEA_SITE/swideaSite/templates/sites/devtlist.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <title>개발툴 관리</title>
  </head>
  <body>
    <nav>
      <a href="">My SW Idea Manage</a>
      <a href="{% url 'sites:ideacreate' %}">아이디어 등록</a>
      <a href="{% url 'sites:main' %}">아이디어 관리</a>
      <a href="{% url 'sites:devtcreate' %}">개별툴 등록</a>
      <a href="{% url 'sites:devtlist' %}">개별툴 관리</a>
    </nav>
    <main>
      <div>
        <div>
          <span>DevTool List</span>
          <p>
            개발툴 목록 페이지입니다. 자신이 사용가능한 개발들의 목록을 확인해
            보세요.
          </p>
        </div>
        {% for devtool in devtools %}
        <div>
          <a href="{% url 'sites:devtdetail' devtool.id%}">{{devtool.name}}</a>
          <span>{{devtool.kind}}</span>
          <span>{{devtool.content}}</span>
        </div>
        {% endfor %}
      </div>
    </main>
  </body>
</html>

SWIDEA_SITE/swideaSite/templates/sites/devtupdate.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>개발툴 수정</title>
  </head>
  <body>
    <nav>
      <a href="">My SW Idea Manage</a>
      <a href="{% url 'sites:ideacreate' %}">아이디어 등록</a>
      <a href="{% url 'sites:main' %}">아이디어 관리</a>
      <a href="{% url 'sites:devtcreate' %}">개별툴 등록</a>
      <a href="{% url 'sites:devtlist' %}">개별툴 관리</a>
    </nav>
    <form
      action="{% url 'sites:devtupdate' devtool.id%}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <h2>
        이름:
        <input type="text" name="name" value="{{devtool.name}}" />
      </h2>
      <p>
        종류:
        <input type="text" name="kind" value="{{devtool.kind}}" />
      </p>
      <p>
        개발툴 설명:
        <textarea name="content" id="" cols="30" rows="10">
{{devtool.content}}</textarea
        >
      </p>
      <div>
        <input type="submit" value="SUBMIT" />
      </div>
    </form>
  </body>
</html>

SWIDEA_SITE/swideaSite/templates/sites/ideadetail.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>아이디어 상세</title>
  </head>
  <body>
    <article>
      {% if idea.image %}
      <p>
        <img src="{{ idea.image.url }}" alt="" />
      </p>
      {% endif %}
      <h2>{{ idea.title }}</h2>
      <p>1) 아이디어 관심도</p>
      <p>{{idea.interest}}</p>
      <p>2) 예상 개발 툴</p>
      <p>{{devt_name}}</p>
      <div>{{idea.content}}</div>
    </article>

    <div><a href="{% url 'sites:ideaupdate' idea.id %}">수정</a></div>
    <div>
      <form action="{% url 'sites:ideadelete' idea.id %}" method="post">
        {% csrf_token %}
        <button>삭제</button>
      </form>
    </div>
    <div><a href="/">목록</a></div>
  </body>
</html>

SWIDEA_SITE/swideaSite/templates/sites/ideaupdate.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>아이디어 수정</title>
  </head>
  <body><nav>
    <a href="">My SW Idea Manage</a>
    <a href="{% url 'sites:ideacreate' %}">아이디어 등록</a>
    <a href="{% url 'sites:main' %}">아이디어 관리</a>
    <a href="{% url 'sites:devtcreate' %}">개별툴 등록</a>
    <a href="{% url 'sites:devtlist' %}">개별툴 관리</a>
  </nav>
  <form
    action="{% url 'sites:ideaupdate' idea.id%}"
    method="post"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <h2>
      아이디어 명:
      <input type="text" name="title" value="{{idea.title}}"/>
    </h2>
    <p>
      Image:
    </p>
    <p>Currently: {{idea.image.url}}
      <input type="checkbox" name="clear" value="clear" id="clear"><label for="clear">clear</label></p>
    <p>
    <p>Change:
        <input type="file" name="image"/>
    </p>
    <p>
      아이디어 설명:
      <textarea name="content" id="" cols="30" rows="10">{{idea.content}}</textarea>
    </p>
    <p>
      아이디어 관심도:
      <input type="number" name="interest" value ="{{idea.interest}}"/>
    </p>
    <p>
      예상 개발툴:
      <select name="devtool">
        <option value="{{devt_name}}">{{devt_name}}</option>
        {% for devtool in devtools %}
        {% if devtool.name != devt_name %}
        <option value="{{devtool.name}}">{{devtool.name}}</option></p>
        {% endif %}
        {% endfor %}
      </select>
    </p>

    <div>
      <input type="submit" value="SUBMIT" />
    </div>
  </form></body>
</html>

SWIDEA_SITE/swideaSite/templates/sites/main.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>아이디어 사이트</title>
  </head>
  <body>
    <nav>
      <a href="">My SW Idea Manage</a>
      <a href="">아이디어 등록</a>
      <a href="">아이디어 관리</a>
      <a href="">개별툴 등록</a>
      <a href="">개별툴 관리</a>
    </nav>
    <main>
      <div>
        <div>
          <span>Idea List</span>
          <p>나의 아이디어를 잊지 말고 기록해보세요</p>
        </div>
      </div>
    </main>
  </body>
</html>